
server:
  port: 8777

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lr?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 507119184618-fgap65bp6p579so9hhjtvqd01o2jcbik.apps.googleusercontent.com
            client-secret: 95HioKSFeCxoulTdpHI5BCCI
            scope:
              - email
              - profile
          facebook:
            client-id: 1172207466624493
            client-secret: 47200f088d41efc578caaab9c08a9e1b
            scope:
              - email
              - public_profile
          naver:
            client-id: m5FZh88W_0kbz7gcQCuB
            client-secret: KLWTHDNSgy
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8777/login/oauth2/code/naver
          kakao:
            client-id: f738810ddcb5cc189ec62b38ffd28628
            client-secret: Ne75L6KT07SFJrnvVx8PhM9bunNrSCf0
            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8777/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데, response라는 key값으로 네이버가 리턴 해줌
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

file:
  dir: C:/upload-test-folder/